version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: symfony/maker-bundle
    versions:
    - 1.29.0
    - 1.29.1
    - 1.30.0
    - 1.30.1
  - dependency-name: symfony/routing
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/cache
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/config
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/var-exporter
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/flex
    versions:
    - 1.11.0
    - 1.12.1
  - dependency-name: symfony/polyfill-php80
    versions:
    - 1.22.0
  - dependency-name: symfony/polyfill-intl-idn
    versions:
    - 1.22.0
  - dependency-name: symfony/polyfill-intl-normalizer
    versions:
    - 1.22.0
  - dependency-name: squizlabs/php_codesniffer
    versions:
    - 3.5.8
  - dependency-name: symfony/http-client-contracts
    versions:
    - 2.3.1
